### ISSUE TITLE
Bad request from public URL

### ISSUE THREAD

**Issue by xldrkp** [kns-it/Docker-GitPitch#2]
Hi @baez90, thanks for the image, makes it easier to get started!

The following problem occurs and I do not know if it's Docker related of caused by GitPitch:

When I start up a container *on my local machine* with the following configuration, everything works out fine. I connect to a custom installation of GitLab.

```
version: '3'
services:
  gitpitch:
    image: knsit/gitpitch:latest
    environment:
      - "GP_GITLAB_BASE=https://mygitlab.de/"
      - "GP_GITLAB_API=https://mygitlab.de/api/v4/"
      - "GP_GITLAB_AS_DEFAULT=true"
    ports:
      - 9000:9000
```

I can access my slides with `http://localhost:9000/user/repo`. But when I bring up a container on a Digital Ocean droplet and try the same URL but with the IP of the droplet, I get a Bad Request, saying "Host not allowed".

Appreciate your help, thanks a lot!

**Comment by prskr** [comment]
Hi @xldrkp,

I think it's just a configuration issue (I should update the docs...)

try to launch the container with the following modified docker-compose.yml

```yaml
version: '3'
services:
  gitpitch:
    image: knsit/gitpitch:latest
    environment:
      - "GP_GITLAB_BASE=https://mygitlab.de/"
      - "GP_GITLAB_API=https://mygitlab.de/api/v4/"
      - "GP_GITLAB_AS_DEFAULT=true"
      - "GP_HOST=<your-droplet-ip>"
    ports:
      - 9000:9000
```

When the container is launched the entrypoint uses [gomplate](https://github.com/hairyhenderson/gomplate) to render the application config and evaluates the **GP_HOST** env variable for the allowed hosts.

Let me know if that resolves your problem ;-)
