### ISSUE TITLE
PITCHME.yaml ignored when accessing private repo (GitLab CE)

### ISSUE THREAD

**Issue by xldrkp** [kns-it/Docker-GitPitch#3]
Hi @baez90,

I was successful connecting to an installation of GitLab CE: The slides make use of my custom CSS and the config in the PITCHME.yaml.

Now the problem: After making the repo private and configuring GitPitch with an access token, the slides are shown, but all configuration is ignored. Neither the logo is being loaded nor the custom css. It looks like no other file is being pulled from the API but PITCHME.md.

Here my configuration:

```
version: '3'
services:
  gitpitch:
    image: knsit/gitpitch:latest
    environment:
      - "GP_GITLAB_BASE=https://mygitlab.de/"
      - "GP_GITLAB_API=https://mygitlab.de/api/v4/"
      - "GP_GITLAB_AS_DEFAULT=true"
      - "GP_HOST=X.X.X.X:9000"
      - "GP_GITLAB_ACCESS_TOKEN=asdfasdfasdfasdf"
    ports:
      - 9000:9000
```
