### ISSUE TITLE
Gitpitch says "Bad Request" "Host not allowed"

### ISSUE THREAD

**Issue by kujiy** [kns-it/Docker-GitPitch#7]
I'm trying to use this image for the env below

- gitpitch:
     - virtualbox vm: 192.168.0.27
- gitlab:
     - gitlab.com
     - secret repository

My gitpitch seems to work well but shows "Host not allowed" 

![2018-09-30 22 12 37](https://user-images.githubusercontent.com/6756543/46257968-fa4e3700-c4fd-11e8-8724-1ffc70be4879.png)

```
version: '3'
services:
  gitpitch:
    image: knsit/gitpitch:latest
    environment:
      - "GP_GITLAB_BASE=https://gitlab.com/"
      - "GP_GITLAB_API=https://gitlab.com/api/v4/"
      - "GP_GITLAB_ACCESS_TOKEN=aaaaaaaaaaaaaaaaaaaaa"
      - "GP_GITLAB_AS_DEFAULT=true"
    ports:
      - 9000:9000
```

I tried to change hostname, allowedOrigin and GP_HOST in application.conf but anything got well. Does anyone have an idea?
